version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    image: node:16.14.0
    container_name: web
    network_mode: host
    build: 
      context: .
    volumes:
      - ./:/app
    command: bash -c 'ls -la && pwd && npm start'
    ports:
      - "80:80"
    env_file:
      - ./.env
    restart: always
    depends_on: 
      - postgres