version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    image: node:16.14.0
    container_name: web
    volumes:
      - ./:/app
    command: bash -c 'ls -la && pwd && npm start'
    working_dir: /app
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on: 
      - postgres