version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - network_test
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    container_name: web
    build: 
      context: .
    volumes:
      - ./:/app
    command: bash -c 'ls -la && pwd && npm start'
    ports:
      - "80:80"
    env_file:
      - ./.env
    restart: always
    networks:
      - network_test
    depends_on: 
      - postgres
networks:
  network_test:
    driver: bridge